### ISSUE TITLE
MultiBuild 2.0.6: Copying elevated belts and stacked buildings is broken, it overlaps some and ignores others

### ISSUE THREAD

**Issue by EpicPartyGuy** [DysonSphereMod/QOL#18] opened 2021-03-16 20:43 UTC
As it says in the title, belts aren't copied correctly if they are not on the ground level.
![image](https://user-images.githubusercontent.com/80789173/111376973-858ff880-8676-11eb-9e1c-d7cddb0ec7a8.png)
On the left was copied, on the right was pasted.

![image](https://user-images.githubusercontent.com/80789173/111377181-ba9c4b00-8676-11eb-8f92-1057564cce2a.png)
Top was copied, bottom was pasted.

**Comment by chrisrico** [comment] 2021-03-17 06:06
This is a duplicate of #15

**Comment by brokenmass** [comment] 2021-03-19 15:57
Multilevel belts blueprinting is available in version 2.1.1 and later

**Closed by brokenmass** 2021-03-19 15:57 UTC

**Comment by chrisrico** [comment] 2021-03-19 16:02
Just want to say that you are a damned rock star!
